// this file is autogenerated - any modification will be overwritten
// unused symbols will not be linked in the final binary
// generated on 2023-02-10 15:01:02
// by ['tool/cert.py', '-s', 'qyapi.weixin.qq.com']

#pragma once

////////////////////////////////////////////////////////////
// certificate chain for qyapi.weixin.qq.com:443

// CN: work.weixin.qq.com => name: work_weixin_qq_com
// not valid before: 2022-04-06 00:00:00
// not valid after:  2023-05-07 23:59:59
const char fingerprint_work_weixin_qq_com [] PROGMEM = "44:13:f9:24:12:4c:63:e9:d1:70:aa:be:da:5c:6b:65:32:57:6e:96";
const char pubkey_work_weixin_qq_com [] PROGMEM = R"PUBKEY(
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqMBbmOnDxISTdFSILNd2
2EdThR462NuuXmn6QU/4aztG2PLPIxRarfsutnco1LR6LPLIk1FBNcZszZBk2t/V
tUMfYod+NfcTSYb2xSYr9NnPRnBEbghWr6BpQM54Nw02IvhusrOceUNrOu534AwM
oSBgzRpx1UAuJdY2bVoa9ZRqY9hFHwc+nVV8mxpjLB+eNmOuJTOCNUVl7GpZtQoz
Brj9ZGII0vWEEjDWzWwa67mp3MaCJTUJ3azRFFVAiwospVhbrWFuy1MKEzQkfB+O
oTKkzbN4n54qQyiSBW/VFcx9DT4CZd3d16oesGJ3QPClVWeVynwnhkJLv0EzTCWl
SwIDAQAB
-----END PUBLIC KEY-----
)PUBKEY";

// http://cacerts.digicert.cn/DigiCertSecureSiteCNCAG3.crt
// CN: DigiCert Secure Site CN CA G3 => name: DigiCert_Secure_Site_CN_CA_G3
// not valid before: 2020-03-13 12:00:00
// not valid after:  2030-03-13 12:00:00
const char cert_DigiCert_Secure_Site_CN_CA_G3 [] PROGMEM = R"CERT(
-----BEGIN CERTIFICATE-----
MIIFCDCCA/CgAwIBAgIQBsk1GubwrG6wBvsMKqcyQTANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0yMDAzMTMxMjAwMDBaFw0zMDAzMTMxMjAwMDBaMEwxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJjAkBgNVBAMTHURpZ2lDZXJ0IFNlY3Vy
ZSBTaXRlIENOIENBIEczMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
8FvLH8zXOPwMrB5ZEdaUtfupXVj3ADIIt9uabxZnmnOJVeER4gBDBmuZ/5zvatiK
LqzE05lw03rvSXjiWjAwGSZQWbxz4qUIxGxOpvypsW5tbvcnKkPG9vs2tj+u+KSK
CCMA792c4rroXOBHjlQHl+ET+xnWc3nxobw7yL1vThEcBkCsLiu4BE5eETMzEplu
Z5hVT31EISTkU+L2qoVPqvl2vCLKmb4iKJYHpGIm1qVGRgf54kxfhRl9rEu4k2rQ
eUaJh4r5dKz1y0TFBwLIAM4nwGVc61H5S874Mt1Zw5i2kxnRymMNg5FFuCkQFIrj
UlFvlDohMoBNRvbtzHQAHQIDAQABo4IBzzCCAcswHQYDVR0OBBYEFETZyEozjtNS
jaeSlGEfmsilt+zLMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA4G
A1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEgYD
VR0TAQH/BAgwBgEB/wIBADAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAGGF2h0
dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNuMEAGA1UdHwQ5MDcwNaAzoDGGL2h0dHA6Ly9j
cmwuZGlnaWNlcnQuY24vRGlnaUNlcnRHbG9iYWxSb290Q0EuY3JsMIHOBgNVHSAE
gcYwgcMwgcAGBFUdIAAwgbcwKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2lj
ZXJ0LmNvbS9DUFMwgYoGCCsGAQUFBwICMH4MfEFueSB1c2Ugb2YgdGhpcyBDZXJ0
aWZpY2F0ZSBjb25zdGl0dXRlcyBhY2NlcHRhbmNlIG9mIHRoZSBSZWx5aW5nIFBh
cnR5IEFncmVlbWVudCBsb2NhdGVkIGF0IGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNv
bS9ycGEtdWEwDQYJKoZIhvcNAQELBQADggEBAIEbzergTPhY7dFwqeIB+fRlzYgI
fo40x1uqb+sH3imvCC5V57mSVVPXwEe2hDHCpo2+zGGqot60EkVtLF0+bUpCXffc
3mzVx6ti7GX+znUK5Vh41aoNy1AUara/iWQbcUXo32BrRPmXE+kMzt3VWxQE6ybP
r/l4SAcusEOmuwCTzzkTRttvWCa9VLgY5SsZ0jIj+/eRvQJRxv8x24/HrTI95OMo
+cTFs6iaigj+k85GmxtbpYEJJ4M8E6AtrBQ/i6/jhVY5RssEcxn0sUEvl8Lpxnlr
vyedD9l6digYDmB5jATBq8i8aaLiD7gyah3GHeziwuKmebv3CeTy44o+ORM=
-----END CERTIFICATE-----
)CERT";

// end of certificate chain for qyapi.weixin.qq.com:443
////////////////////////////////////////////////////////////

